version: '3'
services:
  flask:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/code
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - db

  angular:
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - flask

  db:
    image: postgres
    restart: always
    volumes:
      - ./backend/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
