version: '3'
services:
  flask:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    depends_on:
      - db

  angular:
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - ./frontend/.env
    depends_on:
      - flask

  db:
    image: postgres
    restart: always
    volumes:
      - ./backend/data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
